version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app-${APP_SLUG}
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - db
        networks:
            - ${APP_SLUG}-network

    # nginx
    nginx:
        image: nginx:alpine
        container_name: nginx-${APP_SLUG}
        restart: unless-stopped
        ports:
            - "${APP_PORT}:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - ${APP_SLUG}-network

    # db mysql
    db:
        image: mysql:5.7.22
        container_name: db-${APP_SLUG}
        platform: linux/x86_64
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
            MYSQL_USER: ${DB_USERNAME:-username}
        volumes:
            - ./.docker/mysql:/var/lib/mysql
        ports:
            - "${DB_PORT}:${DB_PORT}"
        networks:
            - ${APP_SLUG}-network

    # redis
    redis:
        image: redis:latest
        container_name: redis-${APP_SLUG}
        networks:
            - ${APP_SLUG}-network

networks:
    ${APP_SLUG}-network:
        driver: bridge
